{% set version = "1.5" %}

package:
  name: autopep8
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/autopep8/autopep8-{{ version }}.tar.gz
  sha256: 0f592a0447acea0c2b0a9602be1e4e3d86db52badd2e3c84f0193bfd89fd3a43

build:
  noarch: python
  entry_points:
    - autopep8 = autopep8:main
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pycodestyle >=2.3

test:
  commands:
    - autopep8 --help
    - autopep8 --version

about:
  home: https://github.com/hhatto/autopep8
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'A tool that automatically formats Python code to conform to the PEP 8 style guide'
  dev_url: https://github.com/hhatto/autopep8

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
