{% set version = "1.5.2" %}

package:
  name: autopep8
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/autopep8/autopep8-{{ version }}.tar.gz
  sha256: 152fd8fe47d02082be86e05001ec23d6f420086db56b17fc883f3f965fb34954

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autopep8 = autopep8:main
requirements:
  build:
    - python
    - pip
  run:
    - python
    - pycodestyle >=2.5.0

test:
  imports:
    - autopep8
  commands:
    - pip check
    - autopep8 --help
  requires:
    - pip


about:
  home: https://github.com/hhatto/autopep8
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A tool that automatically formats Python code to conform to the PEP 8 style guide
  dev_url: https://github.com/hhatto/autopep8

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
