{% set version = "1.2.4" %}
package:
  name: autopep8
  version: {{ version }}

source:
  fn: autopep8-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/autopep8/autopep8-1.2.4.tar.gz
  sha256: 38e31e266e29808e8a65a307778ed8e402e1f0d87472009420d6d18146cdeaa2

build:
  entry_points:
    - autopep8 = autopep8:main

  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pep8 >=1.5.7

  run:
    - python
    - pep8 >=1.5.7

test:
  commands:
    - autopep8 --help
    - autopep8 --version

about:
  home: https://github.com/hhatto/autopep8
  license: MIT License
  summary: 'A tool that automatically formats Python code to conform to the PEP 8 style guide'

extra:
  recipe-maintainers:
    - pmlandwehr
