{% set name = "autopep8" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cae4bc0fb616408191af41d062d7ec7ef8679c7f27b068875ca3a9e2878d5443

build:
  number: 0
  noarch: python
  entry_points:
    - autopep8 = autopep8:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pycodestyle >=2.6
    - toml

test:
  imports:
    - autopep8
  commands:
    - pip check
    - autopep8 --help
  requires:
    - pip

about:
  home: https://github.com/hhatto/autopep8
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A tool that automatically formats Python code to conform to the PEP 8 style guide
  dev_url: https://github.com/hhatto/autopep8

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
