travis:
  secure:
    BINSTAR_TOKEN: su7fja8NBWVqFiYFkUOfG6dp6b04bwulUOSQ2kg1s3o3DHPFX5yePhIwTdb9X+6fdf3rrppL+6KhWLTa+ztD9RvQ/W1VZub3HsHzVtCOWddl83r1ZZjcLmEUjHEBsqkM7fiNod/zAZs7Q3e9/7NzZQt0mxtRzD+jMBdgc1fwC8JyfNgRRC0O8y3BJBJdC9lWdrWx+SkrCq1sqLAc0sSKSZBSd6H8Zok8fTqw6g4jM0zryf66YLCzUfRQ3RBcfI8G7yXaK90+jGOKhUbGJxgZh0bT8T9YbWHjVY0TwAOTOyRgLQl8Qb30lhyGU21vk74nmFLZFDSvpDXE4rI1rgO5CXoB6Stn3W1ycL0jV/TkLrL4LrvR7n6UVuuIEVtVsjavmAsUMFds8LyuseOfgYVH6Opet7zKuk3MvkrbOpH8JPuM5axStkbpE35jVyTBYhg6dbSXUF8IX+AKolW4/r/6poVLZ7Nrh9c9bmaypfix057B+fdkZOsYGyH8eMpuyuiymGNrQbk5YDGh8TtY8R1qpuu8y0rMGJzStFPuAWUYCvVEFFrvl8uDGJ9QImWJ/f3TAKzuHgMxv/31yeK0x8EDV63q9DJeqXciPg2TNUB7hzoinFkGt9Iyge9byHT5F0cbjjSfFk65zfYLfDea0Dpqp4916XacSVG283CbESZtQgA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
