travis:
  secure:
    BINSTAR_TOKEN: fkD9KDWl3JNsJqVHQPYhZ/gi7w5nNWPchO04zmjZdZxlnl1TfbIW6gkXN8VyoCBUBWgxqqy16u39IkBYSfLVg2QrzFrjqGENV6JS7vjNX7X40vONrUhx0TvWh1RCUAhNCsgn+NL/yyKgMcXCwO1QmGjgl6H7SXSeaIgqmeozLnT4bibT7NGCrGNoqXyZgpdl/nVyG9DrLoWOPIQIKKia/QUZ3rpFqgWoMNywFaoRFTpbg/8qhnoh6TrFr0OKF5KttUrwqvVpgXezMjSuR59K+EGV/1RrqrHAoTm5L53DfJbf+tSt5EWazTym4QTJH5PRMu7wN7Hzolhw/a4w1jvgvbhiqqRK9CjT1JJftjjuhYje1M0cKU/Rs0+TBy21Kim7A3zq4S47/CQKHFl1TQn97VfVGbvnLxWs14eaO9jDiRuYnMhS+xvr5bbxah3YkYMzRBz6PQhm7ncI2rRVvudc3rwGBHwFCFILA4eGGqXkuS2PUjB10nmPQ4Dhd2r5wg2Dm4AG9ZxFGgbudSqdJkYQ1xdc76QB1maXeCQKDirQM+GTh6dbzoPJN0w2ZJ2Ewao+oMO5Al6L3+un0rfSa+EbQrx2ykuMTNMijjhbunmLtoKikWOXcf+7UaduEhuIgGznZoN/H+vH9xF5Gf0PiAUH07qASubNm3XcNRaW1it/exI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
